"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { ThemeProvider, createTheme } from "@mui/material";
import Navbar from "@/components/Navbar/Navbar";
import { LanguageModeContextProvider } from "@/contexts/LanguageModeContext";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  fallback: ["sans-serif"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const theme = createTheme({
  palette: {
    primary: {
      main: "#ff4dcc",
    },
    secondary: {
      main: "#000000",
    },
  },
  typography: {
    fontFamily: "Montserrat, sans-serif",
    fontWeightLight: 300,
    fontWeightRegular: 400,
    fontWeightMedium: 500,
    fontWeightBold: 700,
  },
  components: {
    MuiTextField: {
      styleOverrides: {
        root: {
          "& .MuiOutlinedInput-root": {
            borderRadius: "8px",
            "& fieldset": {
              borderColor: "#ffffff",
            },
            "&:hover fieldset": {
              borderColor: "#ffffff",
            },
            "&.Mui-focused fieldset": {
              borderColor: "#b30080",
            },
            "& .MuiInputBase-icon": {
              color: "#ffffff",
            },
          },
          "& .MuiInputBase-input": {
            color: "#ffffff",
          },
        },
      },
    },
    MuiSelect: {
      styleOverrides: {
        root: {
          borderRadius: "8px",
          "& .MuiOutlinedInput-notchedOutline": {
            borderColor: "#ffffff",
          },
          "&:hover .MuiOutlinedInput-notchedOutline": {
            borderColor: "#ffffff",
          },
          "& .MuiInputBase-input": {
            color: "#ffffff",
          },
          "& .MuiSelect-icon": {
            color: "#ffffff",
          },
        },
      },
    },
    MuiCheckbox: {
      styleOverrides: {
        root: {
          color: "#ffffff",
          "& .MuiSvgIcon-root": {
            fontSize: "30px",
          },
        },
      },
    },
  },
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} h-screen p-0 m-0 box-border`}>
        <ThemeProvider theme={theme}>
          <LanguageModeContextProvider>
            <Navbar />
            {children}
          </LanguageModeContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
